#!/usr/bin/env node

const NexlApp = require('../backend/nexl-app/nexl-app');
const devInterceptor = require('./dev-interceptor');

class NexlDevApp extends NexlApp {
	applyInterceptors() {
		this.nexlApp.use(devInterceptor);
		super.applyInterceptors();
	}

	getFavIconPath() {
		return '../../frontend/src';
	}
}

new NexlDevApp().start();